name: Java Build Template

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and test with Maven (fail on error)
        run: |
          if mvn clean verify --no-transfer-progress; then
            echo -e "\033[0;32m✅ Build and tests passed!\033[0m"
          else
            echo -e "\033[0;31m❌ Build or tests failed!\033[0m"
            exit 1
          fi
