name: Parameterized Docker Linters

on:
  workflow_dispatch:
    inputs:
      dockerfile_path:
        description: 'Path to Dockerfile (relative to root)'
        required: false
        default: 'Dockerfile'
      hadolint_version:
        description: 'Hadolint Docker image version'
        required: false
        default: 'latest'
      fail_on_error:
        description: 'Fail workflow if linting fails (true/false)'
        required: false
        default: 'true'

  push:
    paths:
      - '**/Dockerfile'
  pull_request:
    paths:
      - '**/Dockerfile'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          echo "DOCKERFILE_PATH=${{ github.event.inputs.dockerfile_path || 'Dockerfile' }}" >> $GITHUB_ENV
          echo "HADOLINT_VERSION=${{ github.event.inputs.hadolint_version || 'latest' }}" >> $GITHUB_ENV
          echo "FAIL_ON_ERROR=${{ github.event.inputs.fail_on_error || 'true' }}" >> $GITHUB_ENV

      - name: Run Hadolint
        run: |
          echo "Linting $DOCKERFILE_PATH with Hadolint version $HADOLINT_VERSION"
          if [ "$FAIL_ON_ERROR" = "true" ]; then
            docker run --rm -i \
              -v "$PWD":/dockerfiles \
              hadolint/hadolint:$HADOLINT_VERSION \
              hadolint /dockerfiles/$DOCKERFILE_PATH
          else
            docker run --rm -i \
              -v "$PWD":/dockerfiles \
              hadolint/hadolint:$HADOLINT_VERSION \
              hadolint /dockerfiles/$DOCKERFILE_PATH || true
          fi
