name: Parameterized Docker Linters

on:
  workflow_dispatch:
    inputs:
      dockerfile_path:
        description: 'Path to Dockerfile (relative to repo root)'
        required: false
        default: 'Dockerfile'
      hadolint_version:
        description: 'Hadolint Docker image version'
        required: false
        default: 'latest'
      fail_on_error:
        description: 'Fail workflow if linting fails (true/false)'
        required: false
        default: 'true'

  push:
    paths:
      - '**/Dockerfile'
  pull_request:
    paths:
      - '**/Dockerfile'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 1: Set environment variables for manual trigger
      - name: Set environment variables from manual inputs
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "DOCKERFILE_PATH=${{ github.event.inputs.dockerfile_path }}" >> $GITHUB_ENV
          echo "HADOLINT_VERSION=${{ github.event.inputs.hadolint_version }}" >> $GITHUB_ENV
          echo "FAIL_ON_ERROR=${{ github.event.inputs.fail_on_error }}" >> $GITHUB_ENV

      # Step 2: Set default environment variables for automatic triggers
      - name: Set default environment variables for push/PR
        if: github.event_name != 'workflow_dispatch'
        run: |
          echo "DOCKERFILE_PATH=Dockerfile" >> $GITHUB_ENV
          echo "HADOLINT_VERSION=latest" >> $GITHUB_ENV
          echo "FAIL_ON_ERROR=true" >> $GITHUB_ENV

      # Step 3: Run Hadolint
      - name: Run Hadolint
        run: |
          echo "Linting $DOCKERFILE_PATH with Hadolint version $HADOLINT_VERSION"
          if [ "$FAIL_ON_ERROR" = "true" ]; then
            docker run --rm -i \
              -v "$PWD":/dockerfiles \
              hadolint/hadolint:$HADOLINT_VERSION \
              hadolint /dockerfiles/$DOCKERFILE_PATH
          else
            docker run --rm -i \
              -v "$PWD":/dockerfiles \
              hadolint/hadolint:$HADOLINT_VERSION \
              hadolint /dockerfiles/$DOCKERFILE_PATH || true
          fi
